# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(19191C)
$foreground = rgb(FAF5E8)
$color0 = rgb(404043)
$color1 = rgb(12121C)
$color2 = rgb(464749)
$color3 = rgb(B6687E)
$color4 = rgb(6E86AD)
$color5 = rgb(7DAA79)
$color6 = rgb(B6A98D)
$color7 = rgb(F0E8D5)
$color8 = rgb(A8A295)
$color9 = rgb(181825)
$color10 = rgb(5D5F61)
$color11 = rgb(F38BA8)
$color12 = rgb(92B2E6)
$color13 = rgb(A6E3A1)
$color14 = rgb(F2E1BC)
$color15 = rgb(F0E8D5)
