# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FAF5E8
background         #19191C
cursor             #ACAAA4

active_tab_foreground     #19191C
active_tab_background     #FAF5E8
inactive_tab_foreground   #FAF5E8
inactive_tab_background   #19191C

active_border_color   #FAF5E8
inactive_border_color #19191C
bell_border_color     #12121C

color0      #404043
color1		#12121C
color2		#464749
color3		#B6687E
color4		#6E86AD
color5		#7DAA79
color6		#B6A98D
color7		#F0E8D5
color8		#A8A295
color9		#181825
color10		#5D5F61
color11		#F38BA8
color12		#92B2E6
color13		#A6E3A1
color14		#F2E1BC
color15		#F0E8D5
